export * from "./hotel-c/hotel-c.component"
export * from "./form-hotel/form-hotel.component"
export * from "./profile/profile.component"
export * from "./update-user-form/update-user-form.component"
export * from "./clients-c/clients-c.component"
export * from "./reviews-c/reviews-c.component"
export * from "./reviews-form/reviews-form.component"
